
export const SCREEN_SPLASH = 'SCREEN_SPLASH';
export const SCREEN_CITY_SELECTOR = 'SCREEN_CITY_SELECTOR';
export const SCREEN_MAIN = 'SCREEN_MAIN';

export const SCREEN_STOPS = 'SCREEN_STOPS';
export const SCREEN_STOP_DIRECTIONS = 'SCREEN_STOP_DIRECTIONS';

export const SCREEN_DIRECTIONS = 'SCREEN_DIRECTIONS';
export const SCREEN_DIRECTION_STOPS = 'SCREEN_DIRECTION_STOPS';

export const SCREEN_FAVORITES = 'SCREEN_FAVORITES';
export const SCREEN_FAVORITE_STOP = 'SCREEN_FAVORITE_STOP';
export const SCREEN_FAVORITE_DIRECTION = 'SCREEN_FAVORITE_DIRECTION';

export const SCREEN_SETTINGS = 'SCREEN_SETTINGS';
export const SCREEN_UPDATER = 'SCREEN_UPDATER';
export const SCREEN_SCHEDULE = 'SCREEN_SCHEDULE';

export const SCREEN_MAP = 'SCREEN_MAP';
export const SCREEN_DRAWER = 'SCREEN_DRAWER';